### PR TITLE
Handle string BibTeX month field from Mendeley

### PR DESCRIPTION
**Pull request by baip**
BibTeX exported from Mendeley has months in textual form ("jan", "sep", etc.).

### CODE REVIEW

**Comment by larsgw** [comment]
Sorry for the late response, and thanks for the idea (and the PR)! I think I'll change some things and merge it with dd1a7d7d9afe02ac3a901bd2b4de8c4f107ee4da first. Some more specific feedback:

* I lazily used `parseFloat` because it's safe to use directly as a `Array#map` callback ([while `parseInt` isn't](https://stackoverflow.com/a/262511/5095300)); however, that wouldn't be necessary in `parseDateString`
* I used some more general month name notations in dd1a7d7d9afe02ac3a901bd2b4de8c4f107ee4da (note that those allow `January.`, which I shouldn't have done), so I'll fix and copy that behaviour here
* This code would transform month names in day and year fields, and while that probably wouldn't go wrong, I'd like to change that
* This code also sets date part fields to `undefined` instead of `NaN` if invalid, which is exactly the behaviour I like to avoid with these functions (i.e. making sure other functions can depend on certain fields having certain structures)
* Some style things:
  * Citation.js uses [standardJS style](https://standardjs.com/), which rules the use of 2 space indentation, a space after the `function` keyword and no semicolons (see [CONTRIBUTING.md](https://github.com/larsgw/citation.js/blob/master/CONTRIBUTING.md#pull-requests))

**Comment by larsgw** [comment]
Isn't this fixed in 0.3.4 by dd1a7d7d9afe02ac3a901bd2b4de8c4f107ee4da? (see issue #92)

**Comment by baip** [comment]
Thanks for getting back on the PR, @larsgw! Glad to know you were tracking it on issue #80 , but it looks like that https://github.com/larsgw/citation.js/commit/dd1a7d7d9afe02ac3a901bd2b4de8c4f107ee4da was not merged in 0.3.4. Anyway the 0.3.4 version I installed from npm did not parse the month entry (e.g., "jan", "oct" exported from Mendeley) correctly. And yes, mine was not a pretty fix.. I did a quick browsing of the code in order to make it work for my use case. I appreciate your kind feedback. This is a really great library for handling citation data. Thank you!

**Comment by larsgw** [comment]
Oh right, that commit is actually on the [dev/io](https://github.com/larsgw/citation.js/commits/dev/io) branch (don't know how I missed that). Currently the development of #88 is basically blocking any new release, but I might be able to transfer some older commits to master before and release anyway.

**Comment by baip** [comment]
It is no hurry for me. I just pointed `package.json` to my forked repo in that particular project. I'll just switch when you release. Thanks again for being responsive on the PR!

**Pull request closed without merging**
